### ISSUE TITLE
Consider using the `single_precision` feature in `fast_poisson`

### ISSUE THREAD

**Issue by Kromey** [SET001/bevy_scroller#1]
I notice that your `PoissonGenerator` casts from f32 to f64 when generating the Poisson distribution, and then casts back to f32 when getting the sampled points. You may instead see better performance - and almost certainly cleaner code - if you instead enable the [`single_precision` feature flag](https://docs.rs/fast_poisson/latest/fast_poisson/#features) on the `fast_poisson` crate, as that changes the generator to use f32 itself. This would remove the need to cast to/from f64 entirely.

**Comment by SET001** [comment]
Nice. Thank you )
